// Auth
export const AUTH_LOGIN_CLEAR_ERROR = 'AUTH_LOGIN_CLEAR_ERROR';
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_STOP = 'AUTH_LOGIN_STOP';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGIN_RESUME = 'AUTH_LOGIN_RESUME';

export default { AUTH_LOGIN_CLEAR_ERROR, AUTH_LOGIN_START, AUTH_LOGIN_STOP, AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAIL, AUTH_LOGIN_RESUME };
